name: CI

on: [push]

permissions:
    contents: read

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'
                symfony-version:
                    - 4.4.*
                    - 5.*
                    - 6.*
                    - 7.*
                dependencies:
                    - highest
                exclude:
                    - php: '7.4'
                      symfony-version: 6.*
                    - php: '7.2'
                      symfony-version: 7.*
                    - php: '7.3'
                      symfony-version: 7.*
                    - php: '7.4'
                      symfony-version: 7.*
                    - php: '8.0'
                      symfony-version: 7.*
                    - php: '8.1'
                      symfony-version: 7.*
                include:
                    - php: '8.0'
                      symfony-version: 6.*
                      dependencies: lowest
                    - php: '8.2'
                      symfony-version: 7.*
                      dependencies: lowest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: flex

            - name: Setup Problem Matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Update PHPUnit
              run: composer require --dev phpunit/phpunit ^9.3.9 --no-update
              if: matrix.php == '8.0' && matrix.dependencies == 'lowest'

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Run tests
              run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml

            - name: Upload code coverage
              uses: codecov/codecov-action@v4
              with:
                  file: build/coverage-report.xml
                  token: ${{ secrets.CODECOV_TOKEN }}